version: '3'

services:
  db-techcar:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=username
      - POSTGRESQL_PASSWORD=userpassword
      - POSTGRESQL_DATABASE=dbtechcar